"""Generate the synthesized golden boot ROM from a pinned firmware image.

The boot ROM is the GOLDEN image: the known-good firmware a bare chip runs
when the BOOT_SEL strap is low. It is frozen in silicon, so it is deliberately
NOT regenerated by fw/build.sh -- promoting a new build to golden is an
explicit act:

    python3 gen_boot_rom.py --promote        # current build -> golden/, regen RTL
    python3 gen_boot_rom.py                  # regenerate RTL from golden/ only

`--promote` copies fw/agriasic_fw.hex to fw/golden/agriasic_fw_golden.hex and
records the date, the image's SHA-256 and its size in fw/golden/GOLDEN.md, so
the ROM contents are reproducible and reviewable in version control.

The emitted module is a pure combinational constant table. Synthesis optimises
it into gates -- it does NOT become one flip-flop per stored bit. Unused words
read as the RV32 canonical NOP (0x00000013) so a fetch past the image is
defined rather than whatever the array happened to hold.
"""
import argparse
import datetime
import hashlib
import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
GOLDEN_DIR = HERE / "golden"
GOLDEN_HEX = GOLDEN_DIR / "agriasic_fw_golden.hex"
GOLDEN_DOC = GOLDEN_DIR / "GOLDEN.md"
BUILD_HEX = HERE / "agriasic_fw.hex"
ROM_SV = HERE.parent / "rtl" / "rv32i" / "agriasic_boot_rom.sv"
NOP = 0x00000013


def read_words(path):
    words = []
    for line in path.read_text().split("\n"):
        line = line.strip()
        if line:
            words.append(int(line, 16))
    return words


def promote():
    GOLDEN_DIR.mkdir(exist_ok=True)
    if not BUILD_HEX.exists():
        raise SystemExit(f"no build to promote: {BUILD_HEX} missing (run build.sh first)")
    shutil.copy2(BUILD_HEX, GOLDEN_HEX)
    data = GOLDEN_HEX.read_bytes()
    words = read_words(GOLDEN_HEX)
    GOLDEN_DOC.write_text(
        "# Golden firmware image\n\n"
        "This is the image synthesized into the boot ROM (`rtl/rv32i/agriasic_boot_rom.sv`)\n"
        "and shadow-loaded into IMEM when the BOOT_SEL strap is low. It is frozen at\n"
        "tapeout: promote a new build only when it has passed the full regression.\n\n"
        f"- Promoted: {datetime.date.today().isoformat()}\n"
        f"- Words: {len(words)} ({len(words) * 4} bytes)\n"
        f"- SHA-256 of the hex file: `{hashlib.sha256(data).hexdigest()}`\n\n"
        "Regenerate the ROM RTL from this image with `python3 gen_boot_rom.py`.\n"
    )
    print(f"promoted {BUILD_HEX.name} -> {GOLDEN_HEX.relative_to(HERE)} "
          f"({len(words)} words)")


def generate(num_words):
    if not GOLDEN_HEX.exists():
        raise SystemExit(f"no golden image at {GOLDEN_HEX}; run with --promote first")
    words = read_words(GOLDEN_HEX)
    if len(words) > num_words:
        raise SystemExit(f"golden image is {len(words)} words, ROM holds {num_words}")
    idx_hi = (num_words - 1).bit_length() + 1        # addr_i[idx_hi:2] selects a word
    sha = hashlib.sha256(GOLDEN_HEX.read_bytes()).hexdigest()

    lines = []
    for i, w in enumerate(words):
        lines.append(f"      {num_words.bit_length() - 1 if False else 0}")
    body = "\n".join(
        f"      {_idx(i, num_words)}: data_o = 32'h{w:08X};" for i, w in enumerate(words))

    ROM_SV.write_text(f"""// -----------------------------------------------------------------------------
// Module: agriasic_boot_rom
// Purpose:
//   Golden firmware image, synthesized as a constant table. This is what a
//   bare chip runs: with the BOOT_SEL strap low, agriasic_spi_boot copies
//   these words into the IMEM SRAM at reset and releases the core.
//
//   GENERATED FILE -- do not edit by hand.
//     source : fw/golden/agriasic_fw_golden.hex ({len(words)} words, {len(words) * 4} bytes)
//     sha256 : {sha}
//     regen  : python3 fw/gen_boot_rom.py
//
// Why a table and not a memory array:
//   These are constants, so synthesis maps the case statement into gates --
//   roughly a few thousand for an image this size in 180 nm -- rather than
//   {num_words * 32} storage bits. There is no clock and no reset here; the
//   copier registers the data on its way into the SRAM.
//
// Why shadow-load instead of fetching from the ROM directly:
//   The core always fetches from the IMEM SRAM, so (a) nothing is added to
//   the fetch path's timing, (b) firmware is linked once, at one address, for
//   both boot sources, and (c) IMEM stays WRITABLE after a ROM boot -- a
//   debugger can halt, patch a constant over JTAG and resume, which a
//   fetch-from-ROM arrangement could not do.
//
// Unused words read as the RV32 canonical NOP so a fetch past the image is
// defined rather than undriven.
// -----------------------------------------------------------------------------
module agriasic_boot_rom #(
  parameter int unsigned NUM_WORDS  = {num_words},
  // What the instantiator believes the image length is. Checked below against
  // the table actually generated into this file.
  parameter int unsigned USED_WORDS = {len(words)}
) (
  input  logic [31:0] addr_i,   // byte address; [1:0] ignored (4B aligned)
  output logic [31:0] data_o
);

  localparam int unsigned AddrLsb = 2;
  localparam int unsigned AddrMsb = $clog2(NUM_WORDS) + AddrLsb - 1;

  // Ground truth, rewritten on every regeneration alongside the table below.
  // The shell carries its own ROM_USED_WORDS; if the two ever drift, the copier
  // would load a truncated or over-long image and the chip would silently run
  // something that is not the golden image. Fail loudly instead.
  localparam int unsigned GENERATED_USED_WORDS = {len(words)};

`ifndef SYNTHESIS
  initial
    if (USED_WORDS != GENERATED_USED_WORDS)
      $fatal(1, "agriasic_boot_rom: USED_WORDS (%0d) does not match the generated table (%0d) -- regenerate with fw/gen_boot_rom.py",
             USED_WORDS, GENERATED_USED_WORDS);
`endif

  wire [AddrMsb-AddrLsb:0] word_addr = addr_i[AddrMsb:AddrLsb];

  always_comb begin
    unique case (word_addr)
{body}
      default: data_o = 32'h0000_0013;   // RV32 NOP
    endcase
  end

endmodule
""")
    print(f"wrote {ROM_SV.relative_to(HERE.parent)}: {len(words)} words used of {num_words}")


def _idx(i, num_words):
    width = max(1, (num_words - 1).bit_length())
    return f"{width}'d{i}"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--promote", action="store_true",
                    help="copy the current build to golden/ before generating")
    ap.add_argument("--words", type=int, default=256,
                    help="ROM depth in 32-bit words (default 256 = 1 KiB)")
    args = ap.parse_args()
    if args.promote:
        promote()
    generate(args.words)
